version: '3.0'

services:

  spyder:
    build:
      context: .
      dockerfile: Dockerfile
    image: spyder
    container_name: spyder
    ports:
      - 2022:22
    # command: ['tail', '-f', '/dev/null']
    volumes:
      - .:/home/notebook-user
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]